### ISSUE TITLE
Bulk Checking

### ISSUE THREAD

**Issue by ghost** [BlackRouter/PIDChecker#1]
Is it possibile to check multiple keys? 
Or check keys from file?

**Comment by ja7ad** [comment]
Hi
Project stopped just PID updated, but you can using PIDKey lite : http://www.solidfiles.com/v/xVDMn2wXxKBKB

**Comment by Quikfix73** [comment]
The download page in comment above no longer exists but I had saved PIDKey Lite in my Dropbox so use this page below to download PIDKey Lite v1.64.4 b16

https://www.dropbox.com/s/is1o7vi1jgm924a/PID%20Bulk%20Key%20Checker%201.64.zip?dl=1

I also tested and found a newer version PIDKey Lite v1.64.4 b18 below which I now put in my Dropbox account:

https://www.dropbox.com/s/ilm4mj97ceixrd9/PID%20Bulk%20Key%20Checker%201.64.4%20b18.zip?dl=1

Please note that Chrome might block this file from being downloaded so if it does you will need to go to your chrome://settings/security setting and change your setting temporarily to "No protection" then download the file and change it back to whatever setting you previously had.

Also, many anti-virus companies will flag the exe file as a "A Variant Of Win64/HackTool.KMSAuto..." but this file is safe and does not contain a virus.  You can read more about this here:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win64/AutoKMS

**Comment by ja7ad** [comment]
> The download page in comment above no longer exists but I had saved PIDKey Lite in my Dropbox so use this page below to download PIDKey Lite v1.64.4 b16
> 
> https://www.dropbox.com/s/is1o7vi1jgm924a/PID%20Bulk%20Key%20Checker%201.64.zip?dl=1
> 
> I also tested and found a newer version PIDKey Lite v1.64.4 b17 below:
> 
> https://en.taiwebs.com/windows/download-pidkey-lite-2693.html
> 
> Please note that many anti-virus companies will flag the exe file as a "A Variant Of Win64/HackTool.KMSAuto..." but this file is safe and does not contain a virus. You can read more about this here:
> 
> https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win64/AutoKMS

Microsoft don't happy for KMS tools :)
