### ISSUE TITLE
Is anyone else getting an update error?

### ISSUE THREAD

**Issue by Quikfix73** [BlackRouter/PIDChecker#2]
I keep getting a "Failed to check for updates" error on PID checker v 3.0.0.0

The error details are:

Error trying to save file: Error downloading "https://raw.githubusercontent.com/BlackRouter/PIDChecker/master/Files/wyserver.wys": The underlying connection was closed: An unexpected error occurred on a send.

What is the fix for this?

![1](https://user-images.githubusercontent.com/75220145/116797734-f449d980-aa9d-11eb-99bc-fa5862918117.jpg)

**Comment by WanaGo** [comment]
Yes I am getting this too.

**Comment by ja7ad** [comment]
> I keep getting a "Failed to check for updates" error on PID checker v 3.0.0.0
> 
> The error details are:
> 
> Error trying to save file: Error downloading "https://raw.githubusercontent.com/BlackRouter/PIDChecker/master/Files/wyserver.wys": The underlying connection was closed: An unexpected error occurred on a send.
> 
> What is the fix for this?
> 
> ![1](https://user-images.githubusercontent.com/75220145/116797734-f449d980-aa9d-11eb-99bc-fa5862918117.jpg)

This error is program updater, don't problem for this.
coming soon this error fixed.

**Comment by xmedeko** [comment]
IMO automatic updates are not necessary for this tool. Sufficient solution is just a manual update or just a manual check if update is available.

**Comment by ja7ad** [comment]
> IMO automatic updates are not necessary for this tool. Sufficient solution is just a manual update or just a manual check if update is available.

Update not required, coming soon removed update from PID key checker
