### ISSUE TITLE
Check Windows Server 2016 and 2019

### ISSUE THREAD

**Issue by nononymousse** [BlackRouter/PIDChecker#3]
Hi, is it possible to add a check for Windows Server 2016 and 2019 ? and if not, why ?

**Comment by ja7ad** [comment]
> Hi, is it possible to add a check for Windows Server 2016 and 2019 ? and if not, why ?

PIDKey support Windows Servers 2003 ~ 2019

**Comment by andika207** [comment]
@Ja7ad it doesn't work with Windows XP which is basically the same thing as Server 2003

**Comment by ja7ad** [comment]
Windows server 2003 and xp expired
