### ISSUE TITLE
Keeps cycling and no info is displayed for entered Key

### ISSUE THREAD

**Issue by WanaGo** [BlackRouter/PIDChecker#4]
Hi,

I have tried multiple keys I have from machines here, and none of them do anything. I enter the key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX format, and click Check Key, and it just sits there scrolling at the bottom, and nothing comes up.

If I click Info, then it brings up Info about the machine I am on, but nothing for the entered Key.

![image](https://user-images.githubusercontent.com/759846/127426681-8bd86589-6ecb-4220-8838-05cbe13e99a1.png)

Any idea whats going on?

Update also fails, same as the other persons Issue already raised.

Running as Admin changes nothing.

**Comment by BlackRouter** [comment]
Info show your machine details

در پنجشنبه 29 ژوئیهٔ 2021 در 7:54 James ***@***.***> نوشت:

**Comment by WanaGo** [comment]
Yes I understand, but why is the Check Key not doing anything after I enter the Key I want to check? Nothing comes up, it stays blank.

**Comment by ja7ad** [comment]
> Hi,
> 
> I have tried multiple keys I have from machines here, and none of them do anything. I enter the key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX format, and click Check Key, and it just sits there scrolling at the bottom, and nothing comes up.
> 
> If I click Info, then it brings up Info about the machine I am on, but nothing for the entered Key.
> 
> ![image](https://user-images.githubusercontent.com/759846/127426681-8bd86589-6ecb-4220-8838-05cbe13e99a1.png)
> 
> Any idea whats going on?
> 
> Update also fails, same as the other persons Issue already raised.
> 
> Running as Admin changes nothing.

The error icon is for the program updater, not the problem.

**Comment by WanaGo** [comment]
I am not referring to the error icon.
No key information is shown in the middle when I click Check Key. Nothing happens.
The bottom bar is scrolling, like its loading, but nothing happens. No information appears.

**Comment by ja7ad** [comment]
> I am not referring to the error icon.
> No key information is shown in the middle when I click Check Key. Nothing happens.
> The bottom bar is scrolling, like its loading, but nothing happens. No information appears.

What is the key for product?

**Comment by WanaGo** [comment]
Windows 10 Key from my PC, and other PC's in my house
In this format
XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
I want to check if its Retail, or OEM, or Volume, etc. 
But nothing comes up when I type in the key and click the Check Key button.

**Comment by WanaGo** [comment]
I've tried now on 3 different computers, all do the same thing, it doesn't work when you enter a Key and then click "Check Key". The information box just remains blank.
Is there a fix?

**Comment by ja7ad** [comment]
> I've tried now on 3 different computers, all do the same thing, it doesn't work when you enter a Key and then click "Check Key". The information box just remains blank.
> Is there a fix?

try this https://www.softpedia.com/get/System/System-Info/PID-Key-Checker.shtml

**Comment by WanaGo** [comment]
That is the same thing, but version 3.0.0.0, I have already tried that, as well as 4.0.0.0, both are exactly the same.

**Comment by xmedeko** [comment]
Maybe similar problem with one key: Windows 7 Home OEM key still in use (the machine has been upgraded to Windows 10 years ago). The PID Checker eats 100% CPU, progress bar progressing. It has taken a few minutes, but finally got result:
```
Description    : Windows 7 Home Premium OEM:SLP
Edition ID     : HomePremium
```
(Other keys are after few seconds)

**Comment by ja7ad** [comment]
> Maybe similar problem with one key: Windows 7 Home OEM key still in use (the machine has been upgraded to Windows 10 years ago). The PID Checker eats 100% CPU, progress bar progressing. It has taken a few minutes, but finally got result:
> 
> ```
> Description    : Windows 7 Home Premium OEM:SLP
> Edition ID     : HomePremium
> ```
> 
> (Other keys are after few seconds)

For old windows many time required for calculate key information and API service this windows is soap.

**Comment by xmedeko** [comment]
OK, I understand the API service is slow, but why PID Checker eats 100% CPU meanwhile?

**Comment by ja7ad** [comment]
> OK, I understand the API service is slow, but why PID Checker eats 100% CPU meanwhile?

For calculation, the key needs to compute.
