### ISSUE TITLE
can you release Pkeyconfig of office 2021?

### ISSUE THREAD

**Issue by kolet** [BlackRouter/PIDChecker#5]
hi, can you please release the pkeyconfig of the office 2021 ?

thanks

**Comment by Quikfix73** [comment]
In addition to Office 2021 keys not being recognized from my testing, I've also noticed that Windows 2011 keys are still showing up as Windows 10 keys in most PID checkers out there so I hope this gets fixed soon where PID checkers can differentiate between a Windows 10 and Windows 11 key.

**Comment by ja7ad** [comment]
> hi, can you please release the pkeyconfig of the office 2021 ?
> 
> thanks

Hi, I need pkeyconfig office 2021.
If you have installed office 2021, please find pkeyconfig in installed path and send to my email (Ja7ad@live.com)

**Comment by ja7ad** [comment]
> In addition to Office 2021 keys not being recognized from my testing, I've also noticed that Windows 2011 keys are still showing up as Windows 10 keys in most PID checkers out there so I hope this gets fixed soon where PID checkers can differentiate between a Windows 10 and Windows 11 key.

Windows 11 don't having stable key just use windows 10 key and pkeyconfig windows 11 support PID key checker.

If you have installed office 2021, please find pkeyconfig in installed path and send to my email (Ja7ad@live.com)

**Comment by kolet** [comment]
> > In addition to Office 2021 keys not being recognized from my testing, I've also noticed that Windows 2011 keys are still showing up as Windows 10 keys in most PID checkers out there so I hope this gets fixed soon where PID checkers can differentiate between a Windows 10 and Windows 11 key.
> 
> Windows 11 don't having stable key just use windows 10 key and pkeyconfig windows 11 support PID key checker.
> 
> If you have installed office 2021, please find pkeyconfig in installed path and send to my email ([Ja7ad@live.com](mailto:Ja7ad@live.com))

i thought you had the pkeyconfig  of 2021 (this is what i was asking :D )

i will try to get it for you from an installation that i've done and send it here or your email .

**Comment by kolet** [comment]
does this works for you ? 
@Ja7ad 

https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/2021RT/
https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/2021VL/
https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/11-2021VL/
https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/TMP/
https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/VLSC/2021/

**Comment by kolet** [comment]
[office2021.zip](https://github.com/Ja7ad/PIDChecker/files/7775742/office2021.zip)

i guess i found it .
this is all i have 

@Ja7ad

**Comment by ja7ad** [comment]
> does this works for you ? @Ja7ad
> 
> https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/2021RT/ https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/2021VL/ https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/11-2021VL/ https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/TMP/ https://filedn.com/lOX1R8Sv7vhpEG9Q77kMbn0/C2R/VLSC/2021/

This is product installation configure

**Comment by ja7ad** [comment]
> [office2021.zip](https://github.com/Ja7ad/PIDChecker/files/7775742/office2021.zip)
> 
> i guess i found it . this is all i have
> 
> @Ja7ad

I test it and release the next version if it works

thanks

**Comment by ja7ad** [comment]
https://github.com/Ja7ad/PIDChecker/releases/tag/4.0.2

**Comment by kolet** [comment]
> > [office2021.zip](https://github.com/Ja7ad/PIDChecker/files/7775742/office2021.zip)
> > i guess i found it . this is all i have
> > @Ja7ad
> 
> I test it and release the next version if it works
> 
> thanks

so it works ;) ?

awesome , glad i helped ^,^

if you saw there was 2  pkeyconfig-office.xrm-ms  
which one did you use ?
also , there were bunch of other files 

oob.xrm-ms
ul-oob.xrm-ms
ul-phn.xrm-ms
ppd.xrm-ms
pl.xrm-ms

what are thoses ?
